--// File Generated By Fox-Warrior's Resources Generator Version 2.05 \\--

if SERVER then

	resource.AddFile( "models/player/slow/santa_claus/slow_fix.mdl" )
	
	resource.AddFile( "materials/models/player/slow/santa_claus/slow_santa.vmt" )
	resource.AddFile( "materials/models/player/slow/santa_claus/slow_santa.vtf" )
	resource.AddFile( "materials/models/player/slow/santa_claus/slow_santa_bump.vtf" )
	resource.AddFile( "materials/models/player/slow/santa_claus/slow_santa_cloth.vmt" )
	resource.AddFile( "materials/models/player/slow/santa_claus/slow_santa_cloth.vtf" )
	resource.AddFile( "materials/models/player/slow/santa_claus/slow_santa_detail.vtf" )
	
	resource.AddFile( "materials/ccommands/present.vmt" )
	resource.AddFile( "materials/ccommands/present.vtf" )
	
end